export type Sample = { prompt: string; criteria: string }

// Sample tasks are written per agent, because a judge can only be strict when
// the criteria name something checkable. Vague criteria produce vague verdicts.
export const SAMPLES: Record<string, Sample[]> = {
  scribe: [
    { prompt: "Write a punchy 5-tweet thread explaining how Rialo's native webcalls let smart contracts call AI agents directly, with no oracles. Audience: crypto builders. Strong hook first, clear CTA last.",
      criteria: "Exactly 5 tweets numbered 1/5 to 5/5, each under 280 characters. Accurate about Rialo, an L1 blockchain by Subzero Labs, not the city Rialto. Strong opening hook and a clear closing call to action." },
    { prompt: "Write a 150 word product announcement for an on-chain labor market where AI agents are paid in escrow and judged automatically.",
      criteria: "Between 130 and 170 words. Names the three mechanics of escrow, autonomous judging, and deadline refunds. No exclamation marks. Ends with one sentence that states what the reader should do next." },
    { prompt: "Write a cold outreach email to a developer relations lead inviting them to try an agent marketplace built on Rialo.",
      criteria: "Subject line under 60 characters. Body under 120 words. Mentions one concrete benefit and one specific next step. No flattery in the opening sentence." },
    { prompt: "Explain escrow-backed AI agent payments to a reader who has never used a blockchain.",
      criteria: "Under 200 words. Uses one everyday analogy. Contains no jargon unless it is defined in the same sentence. Does not use the words leverage or seamless." },
    { prompt: "Write release notes for a version that adds creator royalties, a one agent per account rule, and a price floor for every listing.",
      criteria: "Three sections with a heading each. Every section states what changed and who it affects. Under 200 words total. Written in past tense." },
    { prompt: "Write a 100 word FAQ answer explaining why a task that misses its deadline is refunded in full instead of paying an insurance claim.",
      criteria: "Between 80 and 120 words. States that no work was delivered, so there is no loss to cover. Mentions that the premium is the only cost. Plain language throughout." },
    { prompt: "Write three headline options and one subheading for a landing page about autonomous agent labor with on-chain reputation.",
      criteria: "Exactly three headlines, each under 60 characters, each with a different angle. One subheading under 120 characters. No headline may contain a colon." },
    { prompt: "Summarize the risk of paying an AI agent before its work is reviewed, in one paragraph aimed at a finance audience.",
      criteria: "One paragraph, between 90 and 130 words. Names at least two distinct risks. Uses no bullet points. Avoids speculation about future regulation." },
    { prompt: "Write a short changelog entry and a matching one sentence tweet for a feature that pays publishers a royalty on every passing task.",
      criteria: "Changelog entry under 60 words. Tweet under 200 characters. Both must state the royalty is taken from inside the reward, so requesters pay no extra." },
    { prompt: "Write onboarding copy for a first time user who has just signed in and has TRLO but has never minted a task.",
      criteria: "Under 120 words. Explains the first three actions in order. Ends without a question. Does not assume the reader knows what escrow means." },
  ],
  coda: [
    { prompt: "Write a TypeScript function that computes an insurance premium from an agent pass rate, a reward, a coverage fraction, and a pool loading factor, and returns null when the agent has fewer than five settled tasks.",
      criteria: "Valid TypeScript with explicit parameter and return types. Returns null below five settled tasks. Caps the resulting rate at 0.24. Includes at least three inline comments explaining the reasoning, not the syntax." },
    { prompt: "Write a pure function that splits a settled reward into a worker share, a publisher royalty, and a protocol fee, and never lets the three parts exceed the reward.",
      criteria: "Valid TypeScript. Rounds every share to a whole number. Asserts or documents that the parts sum to the reward. Handles a reward of zero without throwing." },
    { prompt: "Write a Node function that safely parses a JSON response and returns a typed result or a descriptive error, without ever throwing.",
      criteria: "Valid TypeScript. Never throws. Returns a discriminated union with an ok field. Includes an example call in a comment." },
    { prompt: "Write a debounce utility in TypeScript that supports cancelling a pending call and preserves the argument types of the wrapped function.",
      criteria: "Valid TypeScript with generics. Exposes a cancel method. Correctly types the wrapped arguments. No use of the any type." },
    { prompt: "Write a SQL query that returns each agent, its number of settled tasks, its pass rate, and its total reward volume, ordered by pass rate descending.",
      criteria: "Valid SQL. Groups by agent. Excludes agents with zero settled tasks. Computes pass rate as a percentage rounded to one decimal place." },
    { prompt: "Write a function that validates an SVG string and rejects it when it contains an external reference, a script, or an embedded raster image.",
      criteria: "Valid TypeScript. Rejects script, foreignObject, iframe, external href, and data image URLs. Returns the reason for rejection, not just a boolean." },
    { prompt: "Write a retry helper with exponential backoff and a maximum total wait, in TypeScript, that stops retrying on client errors.",
      criteria: "Valid TypeScript. Does not retry on a 4xx status other than 429. Respects a maximum total wait. Uses no external dependency." },
    { prompt: "Write a React hook that reads a value from an API on mount, caches it in local storage, and returns a loading flag and a refresh function.",
      criteria: "Valid TypeScript React. Handles the case where local storage is unavailable. Does not update state after unmount. Returns loading, data, and refresh." },
    { prompt: "Write a function that formats a token amount for display, rounding down, and never shows a misleading zero for a nonzero balance.",
      criteria: "Valid TypeScript. Rounds down, never up. Shows a distinct output for a small nonzero amount. Includes at least four test cases in comments." },
    { prompt: "Write an idempotent database insert in TypeScript that publishes a marketplace listing and refuses when the account already owns one.",
      criteria: "Valid TypeScript. Performs the ownership check before the insert. Returns a distinct result for the duplicate case. Does not trust a client supplied identity without comment." },
  ],
  sage: [
    { prompt: "Compare an escrow-backed agent labor market against a reputation-only freelance platform, and state which failure each design leaves unsolved.",
      criteria: "Structured with clear sections. Names at least three points of comparison. States one unsolved failure for each design. No marketing language." },
    { prompt: "Analyse whether charging a premium of thirty percent of expected loss is sustainable for an insurance pool covering agent task failures.",
      criteria: "Shows the arithmetic explicitly. States the assumptions before the conclusion. Identifies at least one condition under which the pool becomes insolvent." },
    { prompt: "Assess the risks of letting a language model judge the work of another language model, and propose two concrete mitigations.",
      criteria: "Names at least three distinct risks. Each mitigation must be specific enough to implement. Distinguishes between bias and capability limits." },
    { prompt: "Explain what a trusted execution environment adds to an on-chain agent runtime, and what it does not protect against.",
      criteria: "Accurate about trusted execution environments. Contains a section listing what remains unprotected. Avoids claiming any absolute guarantee." },
    { prompt: "Evaluate whether a one agent per account rule meaningfully prevents marketplace spam, given that accounts are free to create.",
      criteria: "Reaches a clear verdict. Acknowledges the account creation loophole explicitly. Proposes at least one stronger alternative and states its cost." },
    { prompt: "Summarize the trade-offs between paying an agent immediately on delivery and paying only after an automated review.",
      criteria: "Covers both directions of the trade-off. Names who bears the risk in each case. Ends with a recommendation and the condition that would reverse it." },
    { prompt: "Analyse how a five percent creator royalty changes the incentive to publish a low quality agent.",
      criteria: "Reasons about incentives, not intentions. Considers the case where the publisher hires their own agent. States whether the royalty alone is sufficient." },
    { prompt: "Research and explain why an oracle is normally required for a smart contract to reach an external service, and what changes when the chain can make web calls natively.",
      criteria: "Accurate about oracles. Explains the trust assumption an oracle introduces. States at least one new risk created by native web calls." },
    { prompt: "Assess whether reputation computed from a pass rate is gameable, and describe the cheapest attack you can find.",
      criteria: "Describes a concrete attack with its cost. States what the attacker gains. Proposes a defence and admits its limitation." },
    { prompt: "Compare paying an insurance claim from a shared pool against refunding the requester directly from the worker fee.",
      criteria: "Names who is worse off under each model. Considers what happens when the pool is empty. Reaches a verdict with a stated assumption." },
  ],
  pixel: [
    { prompt: "Draw a shield icon with a checkmark inside it, as a single self contained SVG.",
      criteria: "Must contain a shield shape and a checkmark. Use yellow and red. Must be a single self contained SVG with a viewBox." },
    { prompt: "Draw a simple house with a triangular roof, a rectangular door, and one square window, as a single SVG.",
      criteria: "Must contain a triangle for the roof, a rectangle for the door, and a square window. Use brown and blue. Single self contained SVG with a viewBox." },
    { prompt: "Draw an upward trending line chart with three data points and a horizontal baseline, as a single SVG.",
      criteria: "Must contain a polyline rising left to right, three visible point markers, and a straight baseline. Use green for the line. Single self contained SVG with a viewBox." },
    { prompt: "Draw a padlock icon with a closed shackle and a keyhole, as a single SVG.",
      criteria: "Must contain a rounded rectangle body, an arc shackle above it, and a circular keyhole. Use gray and yellow. Single self contained SVG with a viewBox." },
    { prompt: "Draw a wallet icon with a card sticking out of the top, as a single SVG.",
      criteria: "Must contain a rectangular wallet body and a second rectangle offset above it. Use brown and white. Single self contained SVG with a viewBox." },
    { prompt: "Draw a five pointed star inside a circle, centered, as a single SVG.",
      criteria: "Must contain exactly one circle and one five pointed star fully inside it. Use yellow for the star and black for the circle outline. Single self contained SVG with a viewBox." },
    { prompt: "Draw a cloud with three raindrops falling below it, as a single SVG.",
      criteria: "Must contain a cloud made of overlapping circles and exactly three separate drop shapes below it. Use gray and blue. Single self contained SVG with a viewBox." },
    { prompt: "Draw a document icon with a folded corner and three horizontal text lines, as a single SVG.",
      criteria: "Must contain a rectangle page, a folded corner in the top right, and exactly three horizontal lines. Use white and gray. Single self contained SVG with a viewBox." },
    { prompt: "Draw a simple bar chart with four bars of increasing height and an axis line, as a single SVG.",
      criteria: "Must contain exactly four rectangles of increasing height sharing a baseline, plus one axis line. Use orange for the bars. Single self contained SVG with a viewBox." },
    { prompt: "Draw a bell notification icon with a small dot badge in the top right, as a single SVG.",
      criteria: "Must contain a bell shape, a small clapper below it, and a filled circle badge in the top right. Use yellow and red. Single self contained SVG with a viewBox." },
  ],
}

// Community agents have no curated set, so these stay deliberately neutral.
export const GENERIC: Sample[] = [
  { prompt: "Produce a short, structured answer to a realistic request in your area of expertise, aimed at a reader who is competent but new to the topic.",
    criteria: "Under 250 words. Structured with clear sections. Contains at least one concrete example. No filler sentences." },
  { prompt: "Explain the most common mistake people make in your area of expertise, and how to avoid it.",
    criteria: "Names one specific mistake, not a general category. Explains why it happens. Gives one actionable correction. Under 200 words." },
  { prompt: "Produce a checklist a beginner can follow to complete a typical task in your area of expertise.",
    criteria: "Between five and eight steps, in order. Each step is a single action. No step depends on knowledge not introduced earlier in the list." },
  { prompt: "Review the following idea and state whether it is sound: paying for work before anyone has checked its quality.",
    criteria: "Reaches a clear verdict. Gives at least two reasons. Names one situation where the opposite verdict would be correct." },
  { prompt: "Write a short brief that another specialist could act on without asking follow up questions.",
    criteria: "States the goal, the constraints, and the definition of done. Under 200 words. Contains no open questions." },
]
